### ISSUE TITLE
Postgres runs into Error - FATAL: role "root" does not exist

### ISSUE THREAD

**Issue by 2bAndi** [camunda/camunda-platform#37] opened 2022-10-07 07:46 UTC
https://github.com/camunda/camunda-platform/blob/8dbf21ac73de6290cc3c6c80f1f2c5df30d55286/docker-compose.yaml#L156

Postgres Error **FATAL: role "root" does not exist**
This can be solved by exchanging the Healty test comannd which is used in the Postgres Section.

` test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]`

**Comment by jessesimpson36** [comment] 2023-04-25 18:08
This is a duplicate of https://github.com/camunda/camunda-platform/issues/31

Closing.

**Closed by jessesimpson36** 2023-04-25 18:08 UTC
