### ISSUE TITLE
wrong path to Postgres data folder

### ISSUE THREAD

**Issue by McAlm** [camunda/camunda-platform#48] opened 2022-10-17 14:21 UTC
postgres-14.5-alpine stores the database files  to /var/lib/postgresql/data, not under /usr/local/postgres/data as in the docker-compose.yaml

therefore the volume mapping needs to be changed to:

```
    volumes:
      - postgres:/var/lib/postgresql/data
```

**Comment by marciojv** [comment] 2023-04-21 13:50
this item is already corrected in the main version! 
Test now!

**Comment by jessesimpson36** [comment] 2023-04-25 18:13
I've confirmed that the latest version does use the proper directory for the postgresql volume. Perhaps this was a problem and was fixed since the issue was posted.

https://github.com/camunda/camunda-platform/blob/main/docker-compose.yaml#L231-L232

proof:
```
> sudo ls /var/lib/docker/volumes/camunda-platform_postgres/_data
base	      pg_dynshmem    pg_logical    pg_replslot	 pg_stat      pg_tblspc    pg_wal		 postgresql.conf
global	      pg_hba.conf    pg_multixact  pg_serial	 pg_stat_tmp  pg_twophase  pg_xact		 postmaster.opts
pg_commit_ts  pg_ident.conf  pg_notify	   pg_snapshots  pg_subtrans  PG_VERSION   postgresql.auto.conf  postmaster.pid
```

I'm going to close this issue. Re-open if I'm wrong in my assessment.

**Closed by jessesimpson36** 2023-04-25 18:13 UTC
