### ISSUE TITLE
Unable to start the process via Message Start Event in Camunda 8 using Python

### ISSUE THREAD

**Issue by Rajput612** [camunda/camunda-platform#13] opened 2022-05-11 05:22 UTC
Hi @menski, @falko @tmetzke and @Zelldon 
My BPMN is as below.
![image](https://user-images.githubusercontent.com/50611037/167346912-9c748db8-b105-497d-894c-a976bcca1b54.png)
Expected Flow

1. an order is created and subsequently a message is created ("In customer lane the process should stop at “Receive the Goods” task.
2. Message is used to check whether the goods are available or not
3. if they are available the goods are deliver to the user and he can receive the goods
4. if the user is happy with the product then the process is completed.
5. if the user is not satisfied then user communicates with us and we try to resolve the issue
6. if we are unable to resolve the issue we pass it on to the seller.

Problems I’m Facing

1. I’m unable to follow the path of Step 2 and Step 6 in both the process i’m trying to move into different lanes and do some stuff 

What i have tried

```
from pyzeebe import ZeebeTaskRouter
from pyzeebe import ZeebeWorker, create_insecure_channel,Job
import asyncio
import random
import nest_asyncio
nest_asyncio.apply()


async def main():
    worker = ZeebeWorker(channel)
    router = ZeebeTaskRouter()
#     ProcessOrderMsg

    async def my_exception_handler(exception: Exception, job: Job) -> None:
        print(exception)
        await job.set_error_status(message= 'itemsOutOfStock', error_code='itemsOutOfStock') 

    @router.task(task_type="Order", exception_handler=my_exception_handler)
    async def Order():
        await client.publish_message(name="ProcessOrderMsg", correlation_key="ProcessOrderMsg")
        return {}

    @router.task(task_type="ProcessOrder", exception_handler=my_exception_handler)
    def ProcessOrder():
        return {}


    @router.task(task_type="DeliverTheGoods", exception_handler=my_exception_handler)
    def DeliverTheGoods():

        return {}
# testMessage
    @router.task(task_type="ReceiveTheGoods", exception_handler=my_exception_handler)
    async def ReceiveTheGoods():
        return {"status":"complain","msg":"success"}

#     EndMsgEvent
    @router.task(task_type="Complain", exception_handler=my_exception_handler)
    async def Complain(msg: str):    

        await client.publish_message(name="ComplaintMessage", correlation_key="ComplaintMessage")


    @router.task(task_type="ProcessComplaint", exception_handler=my_exception_handler)
    async def ProcessComplaint(cool: str):    
        return {"EndMsgEvent1":"EndMsgEvent1"}
    worker.include_router(router)
    await worker.work()
asyncio.run(main())
```
Any Help or guidance will be great help and for any clearification please feel free to ask.

**Comment by menski** [comment] 2022-05-13 13:20
Hi @Rajput612,

I kindly ask you to post such questions in the [User Forum](https://forum.camunda.io/) or the [Slack Community](https://camunda-slack-invite.herokuapp.com/). There our community can help you to root cause your issue, the issue tracker in this repo is only intended for issues related with the content of the repository. 

I'm not familiar with the python zeebe client, but one think I noticed is that you seem to use static correlation key values in your publish message commands, that doesn't look right as the correlation key should match the value inside your process instance. You can read more about [message correlation](https://docs.camunda.io/docs/guides/message-correlation/) in our docs.

I will close this issue, please refer to the forum or slack community for further support regarding your issue.

Best,
Sebastian

**Closed by menski** 2022-05-13 13:20 UTC
